name: YEN GEN MUSIC
favicon: null
layout_spectrum: 0.35550545691512525
typography_spectrum: 0.7069057135377079
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3951940881088376
  lightness: 0.42291047028265893
  saturation: 0.9477393571287394
  rhythmicContrast: 0.8441599865909666
purpose: []
